name: Trivy Dependency Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-dependency:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@master

        with:
          scan-type: 'fs'
          format: 'table'
          scanners: 'vuln'
